# backend:
#   name: git-gateway
#   branch: master

# backend:
#   name: github
#   repo: dobladov/rightsstatements.github.io

backend:
  name: github
  repo: dobladov/testing
  branch: master
  site_domain: testingnotes.netlify.com
  base_url: dobladov.github.io

media_folder: 'images/uploads'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }