backend:
  name: git-gateway
  branch: master

# backend:
#   name: github
#   repo: dobladov/rightsstatements.github.io

media_folder: 'images/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }